binds:
- port: 3002
  tunnelProtocol: direct
  listeners:
  - routes:
    - hostnames: []
      matches: []
      backends:
      - service:
          name: asdf/asdfasdf
          port: 22
        weight: 1
      - service:
          name: default/service
          port: 8080
        weight: 1
      name: yui
      policies:
        cors:
          allowHeaders:
          - mcp-protocol-version
          - content-type
          - cache-control
          allowMethods: []
          allowOrigins:
          - '*'
          exposeHeaders:
          - Mcp-Session-Id
        responseHeaderModifier:
          remove: []
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
      policies:
        cors: {}
- port: 8080
  tunnelProtocol: direct
  listeners:
  - protocol: HTTP
    name: listenerlkjjklkjl
    hostname: '*'
    routes:
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
      policies:
        cors: {}
        requestHeaderModifier: {}
        responseHeaderModifier: {}
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
      policies:
        cors: {}
