binds:
- port: 3001
  listeners:
  - protocol: HTTP
    name: listener1
    namespace: default1
    hostname: '*'
    routes:
    - hostnames: []
      matches:
      - path:
          pathPrefix: /asdf
      backends:
      - service:
          name: asdfsdaf/ddd
          port: 8080
        weight: 1
      name: route
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends:
      - service:
          name: default/service
          port: 8080
        weight: 1
      name: route
  - protocol: HTTP
    name: listener
    hostname: '*'
    routes: []
