binds:
- port: 3003
  tunnelProtocol: direct
  listeners:
  - protocol: HTTP
    name: listener
    hostname: '*'
    routes:
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
    - hostnames:
      - asdf
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: my-route-123
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends:
      - dynamic: {}
        weight: 1
      name: route
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
- port: 8082
  tunnelProtocol: direct
  listeners: []
- port: 8083
  tunnelProtocol: direct
  listeners: []
llm:
  models:
  - name: model-1
    provider: openAI
frontendPolicies: {}
mcp:
  targets: []
