binds:
- port: 8082
  listeners:
  - protocol: TCP
    name: testdsfsdfaaaaabc
    hostname: abcb.com
    tls:
      cert: /asdf
      key: /asdffasdfsdfa
      cipherSuites: []
    tcpRoutes:
    - name: adsfaaaaaaaasdfasdfasdf
      namespace: sadf
      ruleName: d
    - name: test
      namespace: a
      ruleName: asdfasdf
      hostnames:
      - b.com
      backends:
      - weight: 1
        service:
          name: test/abc
          port: 123
    - name: myrouteasdf
      hostnames:
      - b.com
  - protocol: HTTP
    name: lkjlkjl
    hostname: '*'
    routes:
    - matches:
      - path:
          pathPrefix: /
        method: GET
      backends:
      - weight: 1
        dynamic: {}
      name: myrouteabc
      ruleName: test1233
    - matches:
      - path:
          pathPrefix: /
      name: test
      ruleName: asdf
  tunnelProtocol: direct
- port: 8081
  listeners:
  - protocol: HBONE
    name: asdf
    routes:
    - matches:
      - path:
          pathPrefix: /
      name: testasdf
  tunnelProtocol: direct
- listeners: []
  port: 2222
  tunnelProtocol: direct
- listeners: []
  port: 65535
  tunnelProtocol: direct
- listeners: []
  port: 333
  tunnelProtocol: hboneWaypoint
- listeners: []
  port: 121
  tunnelProtocol: direct
- port: 8080
  listeners:
  - protocol: HTTP
    hostname: '*'
    routes: []
