binds:
- port: 3001
  listeners:
  - protocol: HTTP
    name: tests
    namespace: abc
    hostname: '*'
    routes:
    - backends:
      - mcp:
          targets:
          - name: everything
            stdio:
              cmd: npx
              args:
              - '@modelcontextprotocol/server-everything'
          statefulMode: stateless
        weight: 1
      policies:
        cors:
          allowOrigins:
          - '*'
          allowHeaders:
          - mcp-protocol-version
          - content-type
          - cache-control
          exposeHeaders:
          - Mcp-Session-Id
    - hostnames:
      - b.com
      matches:
      - path:
          pathPrefix: /
      backends:
      - dynamic: {}
        weight: 1
      - mcp:
          targets: []
          statefulMode: stateless
        weight: 1
      - service:
          name:
            namespace: default
            hostname: service
          port: 8080
        weight: 1
      name: route123
      ruleName: myrule
      policies:
        requestHeaderModifier:
          remove:
          - asdf
        responseHeaderModifier:
          remove:
          - asdfsdfaasdf
          - abc
        cors:
          allowCredentials: true
          allowHeaders:
          - abc
          allowMethods:
          - GET
          allowOrigins:
          - '*'
          exposeHeaders:
          - abc
          maxAge: 48h
    - hostnames: []
      matches:
      - path:
          pathPrefix: /
      backends: []
      name: route
mcp:
  targets: []
